name: kafka-terraform

on:
  push:
    branches:
      - main # Run on pushes to the main branch
  pull_request:
    branches:
      - main # Run on pull requests to the main branch

jobs:
  terraform:
    name: Terraform-kafka
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_name: ${{ secrets.AIVEN_PROJECT_NAME }}
      TF_VAR_aiven_api_token: ${{ secrets.AIVEN_API_TOKEN }}
      TF_VAR_kafka_user_name: ${{ secrets.KAFKA_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Replace with the Terraform version you need

      - name: Change directory
        working-directory: ./infra/kafka
        run: pwd

      - name: Terraform Init
        working-directory: ./infra/kafka
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra/kafka
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./infra/kafka
        run: terraform apply --auto-approve
